GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6004548dc2661c3398b5f021

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Prateek Saini",
    "subscribedToChannel": "Some Channel"
}

###

DELETE http://localhost:3000/subscribers/6004548dc2661c3398b5f021

###

PATCH http://localhost:3000/subscribers/60045597f0926b2630b4bbb2
Content-Type: application/json

{
    "name": "Ashu Saini"
}